---

- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update cache and install sudo
      ansible.builtin.package:
        name: sudo
        update_cache: true
        state: present
